"""Type stub for the compiled `_feldspar` PyO3 extension (WO-01/WO-02).

`ty`/mypy cannot introspect a native extension module, so this stub is
the one home for its public shape; keep it in lockstep with
`crates/feldspar-py/src/lib.rs`'s `_feldspar` module registration."""

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Set, Tuple

from typani.result import Result

#: The symbolic-kernel canonical-form version (11 sec. 4 R2/R4, WO-22):
#: every derivation/propagation digest that touches canonicalized
#: `Expr` output folds this in.
CANON_VERSION: int

def smoke_span() -> None: ...
def canonical_digest(obj: Any) -> str: ...
def format_f64(x: float) -> str: ...
def exact_accuracy() -> Accuracy: ...
def corner_sweep(
    box: Dict[str, Interval],
    callback: Callable[[Mapping[str, float]], "Result[Mapping[str, float], Any]"],
) -> Dict[str, Interval]: ...
def inflate(iv: Interval, eps: float) -> Interval: ...
def total_error(out_hull: Interval, model_eps: float) -> float: ...
def plan(
    solvers: "list[_PlanSolverInput]",
    known: Dict[str, Interval],
    tags: Set[str],
    target: str,
    eps_budget: float,
    sense: str,
) -> Route: ...
def mech_rect_second_moment(width: float, height: float) -> float: ...
def mech_cantilever_tip_deflection(
    force: float, length: float, youngs_modulus: float, second_moment: float
) -> float: ...
def mech_cantilever_required_youngs_modulus(
    force: float, length: float, second_moment: float, deflection: float
) -> float: ...
def mech_lame_hoop_stress_bore(
    pressure: float, inner_radius: float, outer_radius: float
) -> float: ...
def mech_lame_radial_stress_bore(
    pressure: float, inner_radius: float, outer_radius: float
) -> float: ...
def mech_von_mises_principal(sigma1: float, sigma2: float, sigma3: float) -> float: ...
def mech_bore_von_mises(
    pressure: float, inner_radius: float, outer_radius: float
) -> float: ...
def fluids_reynolds_number(
    density: float, velocity: float, diameter: float, viscosity: float
) -> float: ...
def fluids_laminar_friction_factor(reynolds: float) -> float: ...
def fluids_colebrook_friction_factor(
    reynolds: float, relative_roughness: float
) -> float: ...
def fluids_haaland_friction_factor(
    reynolds: float, relative_roughness: float
) -> float: ...
def fluids_darcy_dp(
    friction_factor: float,
    length: float,
    diameter: float,
    density: float,
    velocity: float,
) -> float: ...
def fluids_minor_loss_dp(k_factor: float, density: float, velocity: float) -> float: ...
def fluids_series_dp(dp1: float, dp2: float) -> float: ...
def fluids_parallel_flow(q1: float, q2: float) -> float: ...
def fluids_pump_operating_flow(
    h0: float, a: float, h_static: float, r: float
) -> float: ...
def fluids_pump_operating_head(h_static: float, r: float, q_star: float) -> float: ...
def fluids_npsh_available(
    p_atm: float,
    p_vapor: float,
    density: float,
    gravity: float,
    static_head: float,
    friction_head: float,
) -> float: ...
def fluids_joukowsky_dp(
    density: float, wave_speed: float, delta_velocity: float
) -> float: ...
def fluids_isentropic_stagnation_temp_ratio(mach: float, gamma: float) -> float: ...
def fluids_isentropic_stagnation_pressure_ratio(mach: float, gamma: float) -> float: ...
def fluids_normal_shock_mach2(mach1: float, gamma: float) -> float: ...
def fluids_normal_shock_pressure_ratio(mach1: float, gamma: float) -> float: ...
def fluids_fanno_function(mach: float, gamma: float) -> float: ...
def heat_plane_wall_resistance(
    thickness: float, conductivity: float, area: float
) -> float: ...
def heat_cylindrical_wall_resistance(
    inner_radius: float, outer_radius: float, conductivity: float, length: float
) -> float: ...
def heat_convection_resistance(coefficient: float, area: float) -> float: ...
def heat_series_resistance(r1: float, r2: float) -> float: ...
def heat_rate_from_resistance(delta_temp: float, resistance: float) -> float: ...
def heat_dittus_boelter_nusselt(
    reynolds: float, prandtl: float, heating: bool
) -> float: ...
def heat_coefficient_from_nusselt(
    nusselt: float, fluid_conductivity: float, diameter: float
) -> float: ...
def invert_for(
    lhs: "Expr", rhs: "Expr", target: str, branch: Optional[str] = None
) -> "Tuple[Expr, str, list[Predicate], str]": ...
def invertible_targets(lhs: "Expr", rhs: "Expr") -> "list[str]": ...
def predicate_to_box(
    predicates: "list[Predicate]",
    declared_box: Dict[str, Interval],
    tags: Set[str],
) -> "Domain": ...
def delta_propagate_symbolic(
    rhs: "Expr", inputs: "List[Tuple[str, float, float]]"
) -> "Normal": ...
def delta_propagate_numeric(
    callback: Callable[[Mapping[str, float]], float],
    inputs: "List[Tuple[str, float, float]]",
    h: float,
) -> "Normal": ...

class CoreErrorRaised(Exception): ...
class UnitErrorRaised(Exception): ...
class DomainViolationRaised(Exception): ...
class PropagationErrorRaised(Exception): ...
class PlanErrorRaised(Exception): ...
class EvalErrorRaised(Exception): ...
class SymbolicErrorRaised(Exception): ...

class Interval:
    def __init__(self, lo: float, hi: float) -> None: ...
    @staticmethod
    def _new_checked(lo: float, hi: float) -> Interval: ...
    @staticmethod
    def _point_checked(x: float) -> Interval: ...
    # Monkey-patched onto this class by feldspar/core.py at import time
    # (01-interfaces `Interval.new`/`Interval.point`); declared here, not
    # reimplemented, so `ty` type-checks core.py's own patch-site
    # assignments and every downstream caller against one signature.
    @staticmethod
    def new(lo: float, hi: float) -> Result[Interval, Any]: ...
    @staticmethod
    def point(x: float) -> Result[Interval, Any]: ...
    @property
    def lo(self) -> float: ...
    @property
    def hi(self) -> float: ...
    def width(self) -> float: ...
    def half_width(self) -> float: ...
    def midpoint(self) -> float: ...
    def contains(self, x: float) -> bool: ...
    def is_subset(self, outer: Interval) -> bool: ...
    def hull(self, other: Interval) -> Interval: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Accuracy:
    def __init__(self, eps_abs: float, eps_rel: float) -> None: ...
    @property
    def eps_abs(self) -> float: ...
    @property
    def eps_rel(self) -> float: ...
    def eps(self, v: float) -> float: ...
    def worst_over(self, iv: Interval) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Dimension:
    def __init__(self, exponents: Tuple[int, int, int, int, int, int, int]) -> None: ...
    @property
    def exponents(self) -> Tuple[int, int, int, int, int, int, int]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Rank:
    kind: str
    n: Optional[int]
    m: Optional[int]
    payload_kind: Optional[str]
    @staticmethod
    def scalar() -> Rank: ...
    @staticmethod
    def complex() -> Rank: ...
    @staticmethod
    def vector(n: int) -> Rank: ...
    @staticmethod
    def tensor(n: int, m: int) -> Rank: ...
    @staticmethod
    def payload(kind: str) -> Rank: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PortDecl:
    name: str
    unit: str
    rank: Rank
    def __init__(self, name: str, unit: str, rank: Optional[Rank] = ...) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Domain:
    def __init__(
        self,
        box: Dict[str, Interval],
        tags: Optional[Set[str]] = ...,
    ) -> None: ...
    @property
    def box(self) -> Dict[str, Interval]: ...
    @property
    def tags(self) -> Set[str]: ...
    def _admits_checked(self, inputs: Dict[str, Interval], tags: Set[str]) -> None: ...
    # Monkey-patched by feldspar/core.py (01-interfaces `Domain.admits`).
    def admits(
        self, inputs: Mapping[str, Interval], tags: Iterable[str]
    ) -> Result[None, Any]: ...

class Expr:
    @staticmethod
    def var(name: str) -> "Expr": ...
    @staticmethod
    def lit(x: float) -> "Expr": ...
    @staticmethod
    def neg(e: "Expr") -> "Expr": ...
    @staticmethod
    def add(items: "list[Expr]") -> "Expr": ...
    @staticmethod
    def mul(items: "list[Expr]") -> "Expr": ...
    @staticmethod
    def sub(a: "Expr", b: "Expr") -> "Expr": ...
    @staticmethod
    def div(a: "Expr", b: "Expr") -> "Expr": ...
    @staticmethod
    def pow(base: "Expr", exp: "Expr") -> "Expr": ...
    @staticmethod
    def sqrt(e: "Expr") -> "Expr": ...
    def canonicalize(self) -> "Expr": ...
    def canonical_string(self) -> str: ...
    def eval(self, inputs: Dict[str, float]) -> float: ...
    def differentiate(self, var: str) -> "Expr": ...

class Normal:
    def __init__(self, mean: float, stddev: float) -> None: ...
    @property
    def mean(self) -> float: ...
    @property
    def stddev(self) -> float: ...
    def to_interval(self) -> Interval: ...

class Predicate:
    def __init__(self, lhs: "Expr", cmp: str, rhs: "Expr") -> None: ...
    def canonical_string(self) -> str: ...

class UnitSystem:
    @staticmethod
    def builtin() -> UnitSystem: ...
    def _dimension_of_checked(self, unit: str) -> Dimension: ...
    def _to_si_checked(self, value: float, unit: str) -> float: ...
    def _from_si_checked(self, value: float, unit: str) -> float: ...
    def compatible(self, a: str, b: str) -> bool: ...
    # Monkey-patched by feldspar/core.py (01-interfaces `UnitSystem`).
    def dimension_of(self, unit: str) -> Result[Dimension, Any]: ...
    def to_si(self, value: float, unit: str) -> Result[float, Any]: ...
    def from_si(self, value: float, unit: str) -> Result[float, Any]: ...

class _PlanSolverInput:
    """WO-05 planning-relevant `SolverInfo` snapshot; built by
    `feldspar/plan/route.py`, carries no `tier` field (FINV-8)."""

    def __init__(
        self,
        solver_id: str,
        inputs: "list[str]",
        outputs: "list[str]",
        domain: Domain,
        cost: float,
        accuracy: Dict[str, Accuracy],
        conservative_for: str,
    ) -> None: ...

class RouteStep:
    @property
    def solver_id(self) -> str: ...
    @property
    def realized_domain(self) -> Domain: ...
    @property
    def predicted_eps(self) -> float: ...
    @property
    def cost(self) -> float: ...

class Route:
    @property
    def target(self) -> str: ...
    @property
    def steps(self) -> "list[RouteStep]": ...
    @property
    def predicted_eps(self) -> float: ...
    @property
    def total_cost(self) -> float: ...
    @property
    def digest(self) -> str: ...
